// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhaTro.Data;

#nullable disable

namespace QuanLyNhaTro.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511035639_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8");

            modelBuilder.Entity("QuanLyNhaTro.Models.DichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HopDongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("TEXT");

                    b.Property<int>("Thang")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TienDichVu")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienDien")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienNuoc")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienPhong")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HopDongId", "Thang", "Nam")
                        .IsUnique();

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NguoiThueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhongId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TienCoc")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NguoiThueId");

                    b.HasIndex("PhongId");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.NguoiThue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NguoiThues");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.Phong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DienTichM2")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaThue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.ThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.HopDong", "HopDong")
                        .WithMany("HoaDons")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.HopDong", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.NguoiThue", "NguoiThue")
                        .WithMany("HopDongs")
                        .HasForeignKey("NguoiThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyNhaTro.Models.Phong", "Phong")
                        .WithMany("HopDongs")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiThue");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.ThanhToan", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.HoaDon", "HoaDon")
                        .WithMany("ThanhToans")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.HoaDon", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.HopDong", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.NguoiThue", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.Phong", b =>
                {
                    b.Navigation("HopDongs");
                });
#pragma warning restore 612, 618
        }
    }
}
